### ISSUE TITLE
Teatud väljad peaksid olema nõutud

### ISSUE THREAD

**Issue by musamees** [mkmarkson/APIviimane#1]
http://robert.vkhk.ee/~mark.markson/users.php
Lehel annab errori, kui ei sisesta regamisel kasutajat.

**Comment by musamees** [comment]
Tegelt kõik väljad, või siis pead tegema nii et enne kuvamist kontrollid kas vastava välja jaoks on olemas sisu.

**Comment by mkmarkson** [comment]
required filds added
